### ISSUE TITLE
Deprecate repo

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hack-series#2]
Since we'll just be redirecting to the Eventbrite, let's (unfortunately) go ahead and deprecate this repo.

Can you add to the repo's description and README that we've deprecated it? (and perhaps say that we're now just linking directly to the Eventbrite?)

**Comment by maxwofford** [comment]
Closed https://github.com/hackclub/hack-series/commit/3afa26e9b0eef0fa9327bcb8b79cb9538ee67ef1
